// Base URL
@Base_Url = http://localhost:3000

### Get Request (Health Check)
GET {{Base_Url}}

### Post Request
POST {{Base_Url}}/auth/signup 
Content-Type: application/json

//Body payload
{
  "name": "Jitendraa Sahoo",
  "email": "Test10@gmail.com",
  "password": "test@1234"
}

### Login Request
POST {{Base_Url}}/auth/login 
Content-Type: application/json

//Body payload
{
  "email": "Test10@gmail.com",
  "password": "test@1234"
}
